//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSystem.DAL.TestSystemModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestMaterial
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ThemeId { get; set; }
        public Nullable<int> DisciplineId { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> InformationId { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual MaterialsInfo MaterialsInfo { get; set; }
        public virtual TestLanguage TestLanguage { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
